services:
  php:
    image: php:8.4-fpm
    build:
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${VITE_PORT:-5174}:${VITE_PORT:-5174}
    volumes:
      - ./:/var/www/laravel
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:latest
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${NGINX_SERVER_HOST_HTTP_PORT:-8080}:80
    #      - ${NGINX_SERVER_HOST_HTTP_PORT:-443}:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #      - ./docker/nginx/ssl:/etc/ssl
      - ./:/var/www/laravel
    depends_on:
      - postgres
      - php
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_PORT: ${DB_PORT:-54322}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DB_DATABASE:-app}", "-U", "${DB_USERNAME:-admin}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - ${DB_PORT:-54322}:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
